#################### default parameters ############################
favicon = "images/favicon.svg"
logo = "images/logo.svg"
logo_darkmode = "images/logo-darkmode.svg"
logo_width = "160px"
logo_height = "32px"
logo_webp = false
logo_text = "Anomalica"
navbar_fixed = true
theme_switcher = true
theme_default = "system"
mainSections = ["people", "events", "places", "organisations", "matters", "objects"]
copyright = "Content: [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) | Code: [MIT](https://opensource.org/licenses/MIT)"

# Navigation button
[navigation_button]
enable = false

# Search
[search]
enable = true
primary_color = "#0B6E6E"
include_sections = ["people", "events", "places", "organisations", "matters", "objects"]
show_image = false
show_description = true
show_tags = true
show_categories = false

[announcement]
enable = false

# SEO
[metadata]
keywords = ["anomalous phenomena", "encyclopaedia", "UAP", "reference"]
description = "Encyclopaedia of Anomalous Phenomena"
author = "Anomalica"
image = "images/og-image.png"

[cookies]
enable = false
