baseURL = "/"
title = "Anomalica"
timeZone = "UTC"
hasCJKLanguage = true
defaultContentLanguage = "en"

[languages.en]
languageName = "English"
languageCode = "en-GB"
weight = 1

[pagination]
pagerSize = 20

[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = "assets/notwatching/hugo_stats\\.json"
target = "css"

[module]
[[module.mounts]]
source = "content/english"
target = "content"

[[module.mounts]]
source = "../anomalica-content/pages"
target = "content/pages"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
disableWatch = true
source = "hugo_stats.json"
target = "assets/notwatching/hugo_stats.json"

[outputs]
home = ["HTML", "RSS"]

[imaging]
quality = 80

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "monokai"
